name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-python-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Check for outdated packages
      run: |
        pip install --upgrade pip
        pip list --outdated
    
    - name: Create pull request for updates
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Python dependencies'
        title: '🔄 Automated Python dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR updates Python dependencies to their latest versions.
          
          Please review the changes and run tests before merging.
        branch: automated/python-deps
        labels: dependencies, automated
  
  update-npm-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Check for outdated packages
      run: |
        cd frontend
        npm outdated || true
    
    - name: Update dependencies
      run: |
        cd frontend
        npx npm-check-updates -u
        npm install
    
    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update npm dependencies'
        title: '🔄 Automated npm dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR updates frontend dependencies to their latest versions.
          
          Please review the changes and run tests before merging.
        branch: automated/npm-deps
        labels: dependencies, automated




